---

- src: https://github.com/superlumic/ansible-role-homebrew.git
  name: roderik.superlumic-homebrew

- src: https://github.com/superlumic/ansible-role-osx-defaults.git
  name: roderik.superlumic-osx-defaults

- src: https://github.com/superlumic/ansible-role-cli.git
  name: roderik.superlumic-cli

- src: https://github.com/superlumic/ansible-role-sublimetext.git
  name: roderik.superlumic-sublimetext

- src: https://github.com/stackedsax/ansible-role-dotfiles.git
  name: stackedsax.ansible-role-dotfiles

