---

- hosts: localhost
  connection: local

  tasks:
    - homebrew_tap:
        name: codekitchen/dinghy
    - homebrew_tap:
        name: caskroom/fonts
    - name: install node
      homebrew: name={{item}} state=latest
      with_items:
        - node
        - docker
        - docker-compose
        - docker-machine
        - docker-machine-driver-xhyve
        - brew-cask-completion
        - dinghy
    - shell: chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
      become: yes
    - shell: chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
      become: yes
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - 1password
        - ableton-live-suite
        - adium
        - alfred
        - appium
        - carbon-copy-cloner
        - cheatsheet
        - cyberduck
        - dropbox
        - firefox
        - font-fira-code
        - google-backup-and-sync
        - google-chrome
        - grammarly
        - handbrake
        - hazel
        - istat-menus
        - iterm2
        - jaxx
        - kaleidoscope
        - karabiner
        - macvim
        - microsoft-office
        - mou
        - omnigraffle
        - paw
        - shiftit
        - skype
        - slack
        - spotify
        - superduper
        - torbrowser
        - tower
        - unrarx
        - utorrent
        - vagrant
        - virtualbox
        - xquartz

    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh

    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config

    - name: personal ssh config in another location
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh/ssh_config

    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^soulgraffiti', line: 'soulgraffiti ALL=(ALL) NOPASSWD: ALL' }

    - name: Git Config | Install git completion
      raw: curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
      tags: git


  roles:
    - profile-all
    - profile-developer
    - stackedsax.ansible-role-dotfiles

  vars:
    - computername: soulg-laptop
    - git_user_name: stackedsax
    - git_user_email: ascammon@hotmail.com
    - sublime_packages:
        - dest: "SideBarEnhancements"
          repo: "https://github.com/titoBouzout/SideBarEnhancements"
          version: "st3"
        - dest: "GitGutter"
          repo: "https://github.com/jisaacks/GitGutter.git"
          version: "master"
        - dest: "BracketHighlighter"
          repo: "https://github.com/facelessuser/BracketHighlighter.git"
          version: "master"
        - dest: "Theme - Soda"
          repo: "https://github.com/buymeasoda/soda-theme.git"
          version: "master"
        - dest: "Theme - Monokai Extended"
          repo: "https://github.com/jonschlinkert/sublime-monokai-extended.git"
          version: "master"
        - dest: "Base16"
          repo: "https://github.com/chriskempson/base16-textmate.git"
          version: "master"
        - dest: "ApplySyntax"
          repo: "https://github.com/facelessuser/ApplySyntax.git"
          version: "master"
        - dest: "SublimeAllAutocomplete"
          repo: "https://github.com/alienhard/SublimeAllAutocomplete"
          version: "master"
        - dest: "Ansible"
          repo: "https://github.com/clifford-github/sublime-ansible.git"
          version: "master"
    - sublime_text_color_scheme: "Packages/Base16/base16-eighties.dark.tmTheme"
    - sublime_text_theme: "Soda Dark 3.sublime-theme"
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'autohide'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'orientation'
        type: string
        value: left
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 2
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'com.apple.menuextra.clock'
        key: 'DateFormat'
        type: string
        value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'PMPrintingExpandedStateForPrint'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
      - domain: 'NSGlobalDomain'
        key: 'NSQuitAlwaysKeepsWindows'
        type: boolean
        value: false
      - domain: 'com.apple.desktopservices'
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      - domain: 'com.apple.print.PrintingPrefs'
        key: 'Quit When Finished'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeInternalDebugMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeDevelopMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'WebKitDeveloperExtras'
        type: boolean
        value: true
