---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present
      
- name: tap caskroom/versions
  homebrew_tap: tap=homebrew/dupes state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - htop-osx
    - watch
    - rsync
    - git-flow
    - ant
    - nano

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java6
    - java7
    - java


- name: install virtualenv
  pip: name=virtualenv
  
- name: install virtualenvwrapper
  pip: name=virtualenvwrapper
