---

- name: get battleschool playbooks
  git: repo=https://github.com/spencergibb/ansible-osx.git dest=roles/profile-developer/tasks/ansible-osx
  tags: git
  - include: ansible-osx/virtualbox.yml
  - include: ansible-osx/vagrant.yml

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - htop-osx
    - watch
    - rsync
    - git-flow
    - ant

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java6
    - java7
    - java
