---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present
      
- name: tap caskroom/versions
  homebrew_tap: tap=homebrew/dupes state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - wget
    - pwgen
    - xmlstarlet
    - htop-osx
    - watch
    - rsync
    - git-flow
    - ant
    - nano

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - java6
    - java7
    - java


- name: install virtualenv
  pip: name={{ item }}
  with_items:
    - virtualenv
  sudo: yes

- name: install virtualenv
  pip: name=virtualenvwrapper extra_args='--ignore-installed six' #extra_args for El Capitan, for the moment
  sudo: yes
  
- name: improved nanorc | checkout repository
  git:
    repo: "https://github.com/scopatz/nanorc.git"
    dest: ~/.nano
    version: "master"
    update: true
  tags: [configuration, nano, improved-nanorc-checkout]

- name: terminal themes | install monokai theme
  git:
    repo: "https://github.com/stephenway/monokai.terminal.git"
    dest: monokai.terminal
    version: "master"
    update: true
  tags: [configuration, theme, terminal]
